owners = ['obviyus']

nickname = "HamVerBot-Dev"
nick_password = "password"
password = "password"
realname = "Steward of #f1"
server = "irc.libera.chat"
port = 6697
use_tls = true
encoding = "UTF-8"
channels = ["#obviyus"]
umodes = "+RB-x"
user_info = "IRC bot for #f1"
version = "irc:git:Rust"
source = "https://github.com/obviyus/hamverbot"
ping_time = 180
ping_timeout = 20
burst_window_length = 8
max_messages_in_burst = 15
should_ghost = false
ghost_sequence = []

[options]
command_prefix = "!"
