CREATE TABLE IF NOT EXISTS drivers_standings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  data TEXT NOT NULL,
  create_time INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS constructors_standings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  data TEXT NOT NULL,
  create_time INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
);