CREATE TABLE IF NOT EXISTS championship_standings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  data TEXT NOT NULL,
  type INTEGER NOT NULL UNIQUE,
  create_time INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
);