name: Build and Release

on:
  push:
    branches:
      - "master"

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/obviyus/hamverbot:${{ github.sha }}
            ghcr.io/obviyus/hamverbot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm i -g semantic-release @semantic-release/changelog @semantic-release/git
          semantic-release
