on:
  push:
    branches:
      - "master"

name: Build and Release

jobs:
  build:
    name: Build HamVerBot

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.0.1"
          prerelease: false
          title: "v0.0.1"
          files: |
              ./target/release/HamVerBot
