name: Build and Release

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build HamVerBot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          npm i -g semantic-release @semantic-release/exec @semantic-release/changelog
          semantic-release
